"""Framework-independent canonical KisanPath domain models."""

from kisanpath.domain.clarification import ClarificationNeed, ClarificationPolicy
from kisanpath.domain.conversation import (
    ConversationState,
    PendingClarification,
    PendingConfirmation,
    WorkflowStage,
    WorkflowTransition,
)
from kisanpath.domain.eligibility import (
    ConfidenceSummary,
    EligibilityOperator,
    EvaluatorType,
    RuleEvaluation,
    RuleResult,
    RuleType,
    SchemeEvaluation,
    SchemeStatus,
)
from kisanpath.domain.eligibility_engine import (
    EligibilityEngine,
    EligibilityEvaluationError,
    SemanticEvaluationRequest,
    SemanticRuleAssessment,
    SemanticRuleEvaluator,
)
from kisanpath.domain.evidence import EvidenceVerifier
from kisanpath.domain.profile import (
    FactProvenance,
    FactStatus,
    FarmerCategory,
    FarmerProfile,
    InputModality,
    IrrigationType,
    LandArea,
    LandNormalizationStatus,
    LandOwnership,
    LandUnit,
    LanguageCode,
    ProfileFact,
    normalize_land_area,
)
from kisanpath.domain.profile_update import (
    ASRAmbiguityProvenance,
    ASRSegmentProvenance,
    ConfirmationCandidate,
    ExtractedLandArea,
    ExtractedValue,
    FieldInputProvenance,
    ProfileExtraction,
    ProfileMergeContext,
    ProfileMerger,
    ProfileMergeResult,
)
from kisanpath.domain.response import (
    LocalizedResponse,
    ResponseComposer,
    ResponseLocalizer,
    ResponsePlan,
    SchemeResponseItem,
)
from kisanpath.domain.scheme import (
    EligibilityRule,
    Jurisdiction,
    PublicationState,
    Scheme,
    SchemeVersion,
    SourcedText,
    SourceReference,
    SourceReviewStatus,
)
from kisanpath.domain.verification import (
    ClaimImportance,
    ClaimVerification,
    ClaimVerificationBatch,
    VerificationStatus,
)

__all__ = [
    "ClaimImportance",
    "ASRAmbiguityProvenance",
    "ASRSegmentProvenance",
    "ClaimVerification",
    "ClaimVerificationBatch",
    "ConfidenceSummary",
    "ClarificationNeed",
    "ClarificationPolicy",
    "ConversationState",
    "ConfirmationCandidate",
    "EligibilityOperator",
    "EligibilityEngine",
    "EligibilityEvaluationError",
    "EligibilityRule",
    "EvaluatorType",
    "EvidenceVerifier",
    "FactProvenance",
    "FactStatus",
    "FieldInputProvenance",
    "FarmerCategory",
    "FarmerProfile",
    "IrrigationType",
    "InputModality",
    "Jurisdiction",
    "LandArea",
    "LandNormalizationStatus",
    "LandOwnership",
    "LandUnit",
    "LanguageCode",
    "LocalizedResponse",
    "PendingConfirmation",
    "PendingClarification",
    "ProfileFact",
    "ProfileExtraction",
    "ProfileMergeContext",
    "ProfileMergeResult",
    "ProfileMerger",
    "PublicationState",
    "ResponseComposer",
    "ResponseLocalizer",
    "ResponsePlan",
    "RuleEvaluation",
    "RuleResult",
    "RuleType",
    "Scheme",
    "SchemeEvaluation",
    "SchemeStatus",
    "SchemeResponseItem",
    "SchemeVersion",
    "SourceReference",
    "SourceReviewStatus",
    "SemanticEvaluationRequest",
    "SemanticRuleAssessment",
    "SemanticRuleEvaluator",
    "SourcedText",
    "VerificationStatus",
    "WorkflowStage",
    "WorkflowTransition",
    "ExtractedLandArea",
    "ExtractedValue",
    "normalize_land_area",
]
