import type { LanguageCode } from "@/lib/contracts";

export const languageNames: Record<LanguageCode, string> = { gu: "ગુજરાતી", hi: "हिन्दी", en: "English" };

const en = {
  skip: "Skip to main content", language: "Language", chooseLanguage: "Choose language",
  primaryNav: "Primary navigation", mobileNav: "Mobile navigation", openNav: "Open navigation",
  assistant: "Assistant", recommendations: "Recommendations", evaluation: "Evaluation", privacy: "Privacy & safety", tryKisanPath: "Try KisanPath",
  heroTitle: "Find the schemes meant for your farm.", heroBody: "Speak naturally. KisanPath checks reviewed conditions, keeps unknowns honest, and shows the evidence behind every recommendation.",
  startVoice: "Start with your voice", typeInstead: "Type instead", reviewedEvidence: "Reviewed evidence", noIds: "No sensitive IDs needed",
  voicePreview: "Voice assistant preview", youSaid: "You said", demoUtterance: "I need support for drip irrigation.", profileFact: "Profile fact", demoLocation: "Anand, Gujarat", confirmed: "confirmed",
  clearerPath: "A clearer path", processTitle: "Speak. Check. Understand.", processBody: "One calm conversation, with deterministic checks and reviewed evidence working underneath.",
  speakTitle: "Speak naturally", speakBody: "Use Gujarati, Hindi, English, or a comfortable mix.", confirmTitle: "Confirm what matters", confirmBody: "We show uncertain location and land values before using them.", reasonTitle: "See the reason", reasonBody: "Every important result maps back to a reviewed condition.",
  inspectEyebrow: "Not a black box", inspectTitle: "A recommendation you can inspect.", inspectBody: "See which facts matched, what is still unknown, which document comes next, and exactly where the condition came from.", exploreDemo: "Explore all demo results",
  guidanceTitle: "Guidance, not an official approval.", guidanceBody: "KisanPath helps you understand reviewed published conditions. The responsible government authority makes the final decision.", unknownStays: "Unknown stays unknown", sourcesVisible: "Sources stay visible", noApplications: "No automatic applications",
  assistantTitle: "Find the right support for your farm", assistantIntro: "Speak naturally. Important values are shown back to you before they affect a result.", privateSession: "Private session · Demo mode", conversation: "Conversation", you: "You",
  welcome: "Hello. What kind of farming support are you looking for? You can speak in Gujarati, Hindi, or English.", voiceIdle: "Tap to speak", voiceListening: "I’m listening…", voiceProcessing: "Understanding your request…", voiceSpeaking: "Reading the response…", voiceRetry: "Try voice again", inputPlaceholder: "Or type here…", send: "Send", preparing: "Preparing your private session…",
  reviewComplete: "Review complete", matches: "{count} schemes may match your situation", resultsBody: "Each result separates confirmed facts, unknowns, and reviewed evidence.", viewResults: "View recommendations", sensitive: "Do not share Aadhaar, bank details, or other sensitive identifiers.", decisionProfile: "Decision profile", relevantFacts: "Only relevant facts", voiceSourceTitle: "Voice facts keep their source.", voiceSourceBody: "Confidence and confirmation remain attached to the canonical profile.", resultsMessage: "I checked your information. I found 3 reviewed demo schemes—each result includes its reason and evidence.",
  voiceStart: "Start voice input", voiceStop: "Stop recording", voiceProcessingLabel: "Processing voice input", voiceStopResponse: "Stop spoken response", voiceRetryLabel: "Retry voice input", voiceFinishHint: "Tap again when you’re done", transcriptHint: "Your transcript is always shown before a decision",
  voiceCheck: "Voice check · {confidence}% confidence", heardCorrectly: "Did we hear your {field} correctly?", ambiguityBody: "The recording could mean either value. We will not use it for eligibility until you confirm.", chooseValue: "Choose the correct value", heardClearly: "heard most clearly", possibleAlternative: "possible alternative", differentValue: "Enter a different value",
  state: "State", district: "District", land: "Land", crop: "Crop", gujarat: "Gujarat", anand: "Anand", threeAcres: "3 acres", thirtyAcres: "30 acres", groundnut: "Groundnut", needsConfirmation: "Needs confirmation",
  checking: "Checking reviewed conditions…", checkingBody: "Profile facts and evidence are checked separately.", emptyTitle: "No reviewed matches yet", emptyBody: "Tell us what support you need and where your farm is located.", errorTitle: "We couldn’t complete that check", retry: "Retry", offline: "You’re offline. Your current profile remains visible; sending is paused.",
  backConversation: "Back to conversation", reviewedProfile: "Reviewed against your confirmed profile", resultsGuidance: "These are guidance results, not official approvals. Open any card to inspect the exact conditions and evidence.", reviewedSources: "{count} reviewed sources", refineProfile: "Refine profile", demoCorpus: "Demo corpus", demoCorpusBody: "These fictional schemes use reviewed synthetic policy records. No real farmer data is shown.", schemeList: "Scheme recommendations",
  strongestMatch: "Strongest reviewed match", conditionsPassed: "{passed} conditions passed", needsAttention: "{count} needs attention", allReviewed: "all reviewed", nextStep: "Next step", whyThis: "Why this?", details: "Details", stopReading: "Stop reading {name}", listenTo: "Listen to {name}", openScheme: "Open {name}",
  likelyEligible: "Likely eligible", notEligible: "Not eligible by a published condition", needInformation: "Need more information", manualReview: "Manual review recommended",
  evidenceDetail: "Evidence detail", closeEvidence: "Close evidence detail", reviewedDemo: "Reviewed demo data", reviewedDemoBody: "This fictional record demonstrates provenance. It is not an active government scheme.", whyMatched: "Why this matched", publishedConditions: "Published conditions", resolved: "{passed}/{total} resolved", evidence: "Evidence", documentReadiness: "Document readiness", officialEvidence: "Official source evidence", reviewedDate: "Reviewed {date}", openSource: "Open source", ready: "ready", needed: "needed", check: "check",
  allRecommendations: "All recommendations", evidenceBacked: "Evidence-backed detail", detailDemoBody: "This is a fictional scheme record for product demonstration, not an active government benefit.", eligibilityConditions: "Eligibility conditions", derivedFrom: "Derived from {sources}", sourceProvenance: "Source provenance", approvedReferences: "{count} approved references", yourNextStep: "Your next step",
  footerTagline: "Evidence-grounded scheme guidance for Indian farmers.", footerDisclaimer: "KisanPath provides guidance based on reviewed published conditions. It does not issue official eligibility decisions.",
  privacyEyebrow: "Clear by design", privacyTitle: "Privacy and safety, in plain language.", privacyLead: "KisanPath only needs facts relevant to scheme discovery. Do not share Aadhaar numbers, bank credentials, or unrelated personal information.", minimumTitle: "Minimum necessary facts", minimumBody: "Farm location, land area, crop, tenure, and the kind of support you need may affect reviewed conditions.", reasoningTitle: "No hidden reasoning", reasoningBody: "We keep operational audit records—sources, rule results, and state changes—not private chain-of-thought.", neverApproval: "Guidance, never approval", neverApprovalBody: "The responsible authority makes the final decision. KisanPath does not submit applications or take financial action.",
  evalEyebrow: "Baseline vs final workflow", evalTitle: "Measured safety, not demo-day intuition.", evalBody: "KisanPath runs the baseline and final system against the same frozen synthetic cases. The result stays reproducible and inspectable.", dataset: "Dataset", evalSnapshot: "Evaluation snapshot", evalNotice: "Seed metrics demonstrate the reporting interface and are not a claim about production performance.", syntheticOnly: "Synthetic cases only", mixedDataset: "Mixed dataset", evalMetrics: "Evaluation metrics", baseline: "Baseline", kisanPath: "KisanPath", safetyTitle: "Zero false-eligibility outcomes in the frozen seed set", safetyBody: "Deterministic failures remained blocking and missing facts triggered clarification.", safetyPassed: "Safety gate passed", frozenDataset: "Frozen synthetic dataset", caseExplorer: "Case explorer", filterLanguage: "Filter cases by language", all: "All", evalCases: "Evaluation cases", sanitizedInput: "Sanitized input", expected: "Expected", actual: "Actual", auditNote: "Audit note", trace: "parse input → update profile → evaluate rules → verify evidence → compose response",
  somethingWrong: "Something went wrong", loadFailed: "We couldn’t load this view.", loadFailedBody: "No profile facts were changed. Retry the safe request when you’re ready.", tryAgain: "Try again", pathMissing: "404 · Path not found", routeMissing: "This route doesn’t lead to a reviewed result.", routeMissingBody: "Return to the assistant and continue your conversation.", openAssistant: "Open assistant",
} as const;

export type TranslationKey = keyof typeof en;
type Catalog = Record<TranslationKey, string>;

const gu: Partial<Catalog> = {
  skip: "મુખ્ય સામગ્રી પર જાઓ", language: "ભાષા", chooseLanguage: "ભાષા પસંદ કરો", primaryNav: "મુખ્ય નેવિગેશન", mobileNav: "મોબાઇલ નેવિગેશન", openNav: "નેવિગેશન ખોલો", assistant: "સહાયક", recommendations: "ભલામણો", evaluation: "મૂલ્યાંકન", privacy: "ગોપનીયતા અને સુરક્ષા", tryKisanPath: "KisanPath અજમાવો",
  heroTitle: "તમારા ખેતર માટેની યોજનાઓ શોધો.", heroBody: "સહજ રીતે બોલો. KisanPath સમીક્ષા કરેલી શરતો તપાસે છે, અજાણી માહિતી અજાણી જ રાખે છે અને દરેક ભલામણ પાછળના પુરાવા બતાવે છે.", startVoice: "અવાજથી શરૂ કરો", typeInstead: "લખીને જણાવો", reviewedEvidence: "સમીક્ષિત પુરાવા", noIds: "સંવેદનશીલ ઓળખ જરૂરી નથી", voicePreview: "વોઇસ સહાયકની ઝલક", youSaid: "તમે કહ્યું", demoUtterance: "મારે ટપક સિંચાઈ માટે સહાય જોઈએ છે.", profileFact: "પ્રોફાઇલ માહિતી", demoLocation: "આણંદ, ગુજરાત", confirmed: "પુષ્ટિ થયેલ",
  clearerPath: "વધુ સ્પષ્ટ માર્ગ", processTitle: "બોલો. તપાસો. સમજો.", processBody: "એક શાંત વાતચીત, જેમાં ચોક્કસ તપાસ અને સમીક્ષિત પુરાવા સાથે કામ કરે છે.", speakTitle: "સહજ રીતે બોલો", speakBody: "ગુજરાતી, હિન્દી, અંગ્રેજી અથવા અનુકૂળ મિશ્રણ વાપરો.", confirmTitle: "મહત્વની માહિતીની પુષ્ટિ કરો", confirmBody: "અનિશ્ચિત સ્થાન અને જમીનના આંકડા વાપરતાં પહેલાં અમે તમને બતાવીએ છીએ.", reasonTitle: "કારણ જુઓ", reasonBody: "દરેક મહત્વપૂર્ણ પરિણામ સમીક્ષિત શરત સાથે જોડાયેલું છે.", inspectEyebrow: "બ્લેક બોક્સ નથી", inspectTitle: "તમે તપાસી શકો એવી ભલામણ.", inspectBody: "કઈ માહિતી મેળ ખાય છે, શું હજુ અજાણ છે, આગળ કયો દસ્તાવેજ જોઈએ અને શરત ક્યાંથી આવી તે જુઓ.", exploreDemo: "બધા ડેમો પરિણામો જુઓ", guidanceTitle: "માર્ગદર્શન, સત્તાવાર મંજૂરી નહીં.", guidanceBody: "KisanPath સમીક્ષિત પ્રકાશિત શરતો સમજવામાં મદદ કરે છે. અંતિમ નિર્ણય જવાબદાર સરકારી સત્તા લે છે.", unknownStays: "અજાણ માહિતી અજાણ જ રહે", sourcesVisible: "સ્ત્રોતો દેખાતા રહે", noApplications: "આપમેળે અરજી નહીં",
  assistantTitle: "તમારી ખેતી માટે યોગ્ય સહાય શોધીએ", assistantIntro: "સહજ રીતે બોલો. મહત્વના આંકડા પરિણામને અસર કરે તે પહેલાં તમને ફરી બતાવવામાં આવે છે.", privateSession: "ખાનગી સત્ર · ડેમો મોડ", conversation: "વાતચીત", you: "તમે", welcome: "નમસ્તે. તમે કઈ ખેતી સહાય શોધી રહ્યા છો? ગુજરાતી, હિન્દી અથવા અંગ્રેજીમાં કહી શકો છો.", voiceIdle: "બોલવા માટે ટેપ કરો", voiceListening: "હું સાંભળી રહ્યો છું…", voiceProcessing: "તમારી વાત સમજી રહ્યો છું…", voiceSpeaking: "જવાબ વાંચી રહ્યો છું…", voiceRetry: "ફરી અવાજ અજમાવો", inputPlaceholder: "અથવા અહીં લખો…", send: "મોકલો", preparing: "તમારું ખાનગી સત્ર તૈયાર થઈ રહ્યું છે…", reviewComplete: "સમીક્ષા પૂર્ણ", matches: "તમારી પરિસ્થિતિ સાથે {count} યોજનાઓ મેળ ખાઈ શકે છે", resultsBody: "દરેક પરિણામ પુષ્ટિ થયેલી માહિતી, અજાણી બાબતો અને સમીક્ષિત પુરાવા અલગ બતાવે છે.", viewResults: "ભલામણો જુઓ", sensitive: "આધાર, બેંક વિગતો અથવા અન્ય સંવેદનશીલ ઓળખ શેર કરશો નહીં.", decisionProfile: "નિર્ણય પ્રોફાઇલ", relevantFacts: "ફક્ત સંબંધિત માહિતી", voiceSourceTitle: "અવાજથી મળેલી માહિતીનો સ્ત્રોત જળવાય છે.", voiceSourceBody: "વિશ્વાસ અને પુષ્ટિ કેનોનિકલ પ્રોફાઇલ સાથે જોડાયેલા રહે છે.", resultsMessage: "તમારી માહિતી તપાસી. 3 સમીક્ષા કરેલી ડેમો યોજનાઓ મળી છે—દરેક પરિણામ સાથે કારણ અને પુરાવો છે.",
  voiceStart: "વોઇસ ઇનપુટ શરૂ કરો", voiceStop: "રેકોર્ડિંગ બંધ કરો", voiceProcessingLabel: "વોઇસ ઇનપુટ પર પ્રક્રિયા ચાલુ છે", voiceStopResponse: "બોલાતો જવાબ બંધ કરો", voiceRetryLabel: "વોઇસ ઇનપુટ ફરી અજમાવો", voiceFinishHint: "બોલી લો ત્યારે ફરી ટેપ કરો", transcriptHint: "નિર્ણય પહેલાં તમારું લખાણ હંમેશા બતાવવામાં આવે છે", voiceCheck: "અવાજ તપાસ · {confidence}% વિશ્વાસ", heardCorrectly: "શું અમે તમારી {field} સાચી સાંભળી?", ambiguityBody: "રેકોર્ડિંગનો અર્થ બેમાંથી કોઈ એક હોઈ શકે છે. તમારી પુષ્ટિ સુધી અમે તેને પાત્રતા માટે વાપરીશું નહીં.", chooseValue: "સાચી કિંમત પસંદ કરો", heardClearly: "સૌથી સ્પષ્ટ સાંભળાયું", possibleAlternative: "શક્ય વિકલ્પ", differentValue: "અલગ કિંમત દાખલ કરો",
  state: "રાજ્ય", district: "જિલ્લો", land: "જમીન", crop: "પાક", gujarat: "ગુજરાત", anand: "આણંદ", threeAcres: "3 એકર", thirtyAcres: "30 એકર", groundnut: "મગફળી", needsConfirmation: "પુષ્ટિ જરૂરી", checking: "સમીક્ષિત શરતો તપાસી રહ્યા છીએ…", checkingBody: "પ્રોફાઇલ માહિતી અને પુરાવા અલગથી તપાસવામાં આવે છે.", emptyTitle: "હજુ કોઈ સમીક્ષિત મેળ નથી", emptyBody: "તમને કઈ સહાય જોઈએ છે અને તમારું ખેતર ક્યાં છે તે જણાવો.", errorTitle: "આ તપાસ પૂર્ણ થઈ શકી નહીં", retry: "ફરી પ્રયાસ કરો", offline: "તમે ઑફલાઇન છો. તમારી હાલની પ્રોફાઇલ દેખાશે; મોકલવાનું રોકાયું છે.",
  backConversation: "વાતચીત પર પાછા જાઓ", reviewedProfile: "તમારી પુષ્ટિ થયેલી પ્રોફાઇલ સામે સમીક્ષિત", resultsGuidance: "આ માર્ગદર્શન છે, સત્તાવાર મંજૂરી નહીં. ચોક્કસ શરતો અને પુરાવા જોવા કોઈપણ કાર્ડ ખોલો.", reviewedSources: "{count} સમીક્ષિત સ્ત્રોતો", refineProfile: "પ્રોફાઇલ સુધારો", demoCorpus: "ડેમો સંગ્રહ", demoCorpusBody: "આ કાલ્પનિક યોજનાઓ સમીક્ષિત કૃત્રિમ નીતિ રેકોર્ડ વાપરે છે. કોઈ વાસ્તવિક ખેડૂતનો ડેટા બતાવવામાં આવ્યો નથી.", schemeList: "યોજનાની ભલામણો", strongestMatch: "સૌથી મજબૂત સમીક્ષિત મેળ", conditionsPassed: "{passed} શરતો પાસ", needsAttention: "{count} પર ધ્યાન જરૂરી", allReviewed: "બધી સમીક્ષિત", nextStep: "આગળનું પગલું", whyThis: "આ કેમ?", details: "વિગતો", stopReading: "{name} વાંચવાનું બંધ કરો", listenTo: "{name} સાંભળો", openScheme: "{name} ખોલો", likelyEligible: "સંભવિત પાત્ર", notEligible: "પ્રકાશિત શરત મુજબ પાત્ર નથી", needInformation: "વધુ માહિતી જરૂરી", manualReview: "મેન્યુઅલ સમીક્ષા સૂચવેલ",
  evidenceDetail: "પુરાવાની વિગત", closeEvidence: "પુરાવાની વિગત બંધ કરો", reviewedDemo: "સમીક્ષિત ડેમો ડેટા", reviewedDemoBody: "આ કાલ્પનિક રેકોર્ડ સ્ત્રોત દર્શાવે છે. આ સક્રિય સરકારી યોજના નથી.", whyMatched: "આ કેમ મેળ ખાય છે", publishedConditions: "પ્રકાશિત શરતો", resolved: "{passed}/{total} ઉકેલાયેલ", evidence: "પુરાવો", documentReadiness: "દસ્તાવેજ તૈયારી", officialEvidence: "સત્તાવાર સ્ત્રોત પુરાવા", reviewedDate: "{date}ના રોજ સમીક્ષિત", openSource: "સ્ત્રોત ખોલો", ready: "તૈયાર", needed: "જરૂરી", check: "તપાસો", allRecommendations: "બધી ભલામણો", evidenceBacked: "પુરાવા આધારિત વિગત", detailDemoBody: "આ પ્રોડક્ટ ડેમો માટેનો કાલ્પનિક યોજના રેકોર્ડ છે, સક્રિય સરકારી લાભ નથી.", eligibilityConditions: "પાત્રતાની શરતો", derivedFrom: "{sources}માંથી તારવેલ", sourceProvenance: "સ્ત્રોતની વિગતો", approvedReferences: "{count} મંજૂર સંદર્ભો", yourNextStep: "તમારું આગળનું પગલું",
  footerTagline: "ભારતીય ખેડૂતો માટે પુરાવા આધારિત યોજના માર્ગદર્શન.", footerDisclaimer: "KisanPath સમીક્ષિત પ્રકાશિત શરતોના આધારે માર્ગદર્શન આપે છે. તે સત્તાવાર પાત્રતા નિર્ણય આપતું નથી.", privacyEyebrow: "રચનાથી જ સ્પષ્ટ", privacyTitle: "ગોપનીયતા અને સુરક્ષા, સરળ ભાષામાં.", privacyLead: "KisanPathને યોજના શોધ માટે સંબંધિત માહિતી જ જોઈએ છે. આધાર નંબર, બેંક ઓળખ અથવા અસંબંધિત વ્યક્તિગત માહિતી શેર કરશો નહીં.", minimumTitle: "ઓછામાં ઓછી જરૂરી માહિતી", minimumBody: "ખેતરનું સ્થાન, જમીનનું ક્ષેત્રફળ, પાક, માલિકી અને જરૂરી સહાય સમીક્ષિત શરતોને અસર કરી શકે છે.", reasoningTitle: "કોઈ છુપાયેલ તર્ક નહીં", reasoningBody: "અમે સ્ત્રોત, નિયમ પરિણામ અને સ્થિતિ ફેરફાર જેવા ઓપરેશનલ ઑડિટ રેકોર્ડ રાખીએ છીએ—ખાનગી વિચારશૃંખલા નહીં.", neverApproval: "માર્ગદર્શન, મંજૂરી નહીં", neverApprovalBody: "અંતિમ નિર્ણય જવાબદાર સત્તા લે છે. KisanPath અરજી સબમિટ કરતું નથી કે નાણાકીય કાર્યવાહી કરતું નથી.",
  evalEyebrow: "બેઝલાઇન વિરુદ્ધ અંતિમ વર્કફ્લો", evalTitle: "માપેલી સુરક્ષા, માત્ર ડેમોની ધારણા નહીં.", evalBody: "KisanPath સમાન સ્થિર કૃત્રિમ કેસો સામે બેઝલાઇન અને અંતિમ સિસ્ટમ ચલાવે છે. પરિણામ પુનઃઉત્પાદિત અને તપાસી શકાય એવું રહે છે.", dataset: "ડેટાસેટ", evalSnapshot: "મૂલ્યાંકન ઝલક", evalNotice: "સીડ મેટ્રિક્સ રિપોર્ટિંગ ઇન્ટરફેસ બતાવે છે અને પ્રોડક્શન કામગીરીનો દાવો નથી.", syntheticOnly: "ફક્ત કૃત્રિમ કેસો", mixedDataset: "મિશ્ર ડેટાસેટ", evalMetrics: "મૂલ્યાંકન માપદંડ", baseline: "બેઝલાઇન", safetyTitle: "સ્થિર સીડ સેટમાં શૂન્ય ખોટી પાત્રતા", safetyBody: "ચોક્કસ નિષ્ફળતાઓ અવરોધક રહી અને ગુમ માહિતી માટે સ્પષ્ટતા પૂછાઈ.", safetyPassed: "સુરક્ષા તપાસ પાસ", frozenDataset: "સ્થિર કૃત્રિમ ડેટાસેટ", caseExplorer: "કેસ એક્સપ્લોરર", filterLanguage: "ભાષા મુજબ કેસ ફિલ્ટર કરો", all: "બધા", evalCases: "મૂલ્યાંકન કેસો", sanitizedInput: "સુરક્ષિત ઇનપુટ", expected: "અપેક્ષિત", actual: "વાસ્તવિક", auditNote: "ઑડિટ નોંધ", trace: "ઇનપુટ સમજો → પ્રોફાઇલ સુધારો → નિયમો તપાસો → પુરાવા ચકાસો → જવાબ બનાવો", somethingWrong: "કંઈક ખોટું થયું", loadFailed: "આ દૃશ્ય લોડ થઈ શક્યું નહીં.", loadFailedBody: "કોઈ પ્રોફાઇલ માહિતી બદલાઈ નથી. તૈયાર હો ત્યારે સુરક્ષિત વિનંતી ફરી અજમાવો.", tryAgain: "ફરી પ્રયાસ કરો", pathMissing: "404 · માર્ગ મળ્યો નથી", routeMissing: "આ માર્ગ કોઈ સમીક્ષિત પરિણામ સુધી જતો નથી.", routeMissingBody: "સહાયક પર પાછા જઈ વાતચીત ચાલુ રાખો.", openAssistant: "સહાયક ખોલો",
};

const hi: Partial<Catalog> = {
  skip: "मुख्य सामग्री पर जाएँ", language: "भाषा", chooseLanguage: "भाषा चुनें", primaryNav: "मुख्य नेविगेशन", mobileNav: "मोबाइल नेविगेशन", openNav: "नेविगेशन खोलें", assistant: "सहायक", recommendations: "सिफारिशें", evaluation: "मूल्यांकन", privacy: "गोपनीयता और सुरक्षा", tryKisanPath: "KisanPath आज़माएँ",
  heroTitle: "अपने खेत के लिए बनी योजनाएँ खोजें।", heroBody: "सहज रूप से बोलें। KisanPath समीक्षा की गई शर्तें जाँचता है, अज्ञात जानकारी को अज्ञात रखता है और हर सिफारिश के पीछे का प्रमाण दिखाता है।", startVoice: "आवाज़ से शुरू करें", typeInstead: "लिखकर बताएँ", reviewedEvidence: "समीक्षित प्रमाण", noIds: "संवेदनशील पहचान की ज़रूरत नहीं", voicePreview: "वॉइस सहायक का पूर्वावलोकन", youSaid: "आपने कहा", demoUtterance: "मुझे ड्रिप सिंचाई के लिए सहायता चाहिए।", profileFact: "प्रोफ़ाइल तथ्य", demoLocation: "आनंद, गुजरात", confirmed: "पुष्ट",
  clearerPath: "एक स्पष्ट रास्ता", processTitle: "बोलें। जाँचें। समझें।", processBody: "एक सहज बातचीत, जिसके पीछे निश्चित जाँच और समीक्षित प्रमाण काम करते हैं।", speakTitle: "सहज रूप से बोलें", speakBody: "गुजराती, हिन्दी, अंग्रेज़ी या सहज मिश्रण का उपयोग करें।", confirmTitle: "ज़रूरी बातों की पुष्टि करें", confirmBody: "अनिश्चित स्थान और भूमि मानों को उपयोग से पहले हम आपको दिखाते हैं।", reasonTitle: "कारण देखें", reasonBody: "हर महत्वपूर्ण परिणाम किसी समीक्षित शर्त से जुड़ा है।", inspectEyebrow: "ब्लैक बॉक्स नहीं", inspectTitle: "ऐसी सिफारिश जिसे आप जाँच सकें।", inspectBody: "देखें कि कौन से तथ्य मिले, क्या अभी अज्ञात है, आगे कौन सा दस्तावेज़ चाहिए और शर्त कहाँ से आई।", exploreDemo: "सभी डेमो परिणाम देखें", guidanceTitle: "मार्गदर्शन, आधिकारिक स्वीकृति नहीं।", guidanceBody: "KisanPath समीक्षित प्रकाशित शर्तों को समझने में मदद करता है। अंतिम निर्णय जिम्मेदार सरकारी प्राधिकरण लेता है।", unknownStays: "अज्ञात, अज्ञात ही रहता है", sourcesVisible: "स्रोत दिखाई देते हैं", noApplications: "स्वचालित आवेदन नहीं",
  assistantTitle: "अपने खेत के लिए सही सहायता खोजें", assistantIntro: "सहज रूप से बोलें। महत्वपूर्ण मान किसी परिणाम को प्रभावित करने से पहले आपको दिखाए जाते हैं।", privateSession: "निजी सत्र · डेमो मोड", conversation: "बातचीत", you: "आप", welcome: "नमस्ते। आप किस तरह की कृषि सहायता खोज रहे हैं? गुजराती, हिन्दी या अंग्रेज़ी में बोल सकते हैं।", voiceIdle: "बोलने के लिए टैप करें", voiceListening: "मैं सुन रहा हूँ…", voiceProcessing: "आपकी बात समझ रहा हूँ…", voiceSpeaking: "जवाब पढ़ रहा हूँ…", voiceRetry: "आवाज़ फिर आज़माएँ", inputPlaceholder: "या यहाँ लिखें…", send: "भेजें", preparing: "आपका निजी सत्र तैयार हो रहा है…", reviewComplete: "समीक्षा पूरी", matches: "{count} योजनाएँ आपकी स्थिति से मेल खा सकती हैं", resultsBody: "हर परिणाम पुष्ट तथ्य, अज्ञात जानकारी और समीक्षित प्रमाण अलग दिखाता है।", viewResults: "सिफारिशें देखें", sensitive: "आधार, बैंक विवरण या अन्य संवेदनशील पहचान साझा न करें।", decisionProfile: "निर्णय प्रोफ़ाइल", relevantFacts: "केवल संबंधित तथ्य", voiceSourceTitle: "आवाज़ से मिले तथ्यों का स्रोत बना रहता है।", voiceSourceBody: "विश्वास और पुष्टि कैनोनिकल प्रोफ़ाइल से जुड़े रहते हैं।", resultsMessage: "आपकी जानकारी जाँची। 3 समीक्षित डेमो योजनाएँ मिलीं—हर परिणाम के साथ कारण और प्रमाण है।",
  voiceStart: "वॉइस इनपुट शुरू करें", voiceStop: "रिकॉर्डिंग रोकें", voiceProcessingLabel: "वॉइस इनपुट संसाधित हो रहा है", voiceStopResponse: "बोला जा रहा जवाब रोकें", voiceRetryLabel: "वॉइस इनपुट फिर आज़माएँ", voiceFinishHint: "पूरा होने पर फिर टैप करें", transcriptHint: "निर्णय से पहले आपकी प्रतिलिपि हमेशा दिखाई जाती है", voiceCheck: "आवाज़ जाँच · {confidence}% विश्वास", heardCorrectly: "क्या हमने आपकी {field} सही सुनी?", ambiguityBody: "रिकॉर्डिंग का अर्थ दोनों में से कोई मान हो सकता है। पुष्टि होने तक हम इसे पात्रता के लिए उपयोग नहीं करेंगे।", chooseValue: "सही मान चुनें", heardClearly: "सबसे स्पष्ट सुना गया", possibleAlternative: "संभावित विकल्प", differentValue: "कोई दूसरा मान दर्ज करें",
  state: "राज्य", district: "ज़िला", land: "भूमि", crop: "फसल", gujarat: "गुजरात", anand: "आनंद", threeAcres: "3 एकड़", thirtyAcres: "30 एकड़", groundnut: "मूंगफली", needsConfirmation: "पुष्टि आवश्यक", checking: "समीक्षित शर्तें जाँची जा रही हैं…", checkingBody: "प्रोफ़ाइल तथ्य और प्रमाण अलग-अलग जाँचे जाते हैं।", emptyTitle: "अभी कोई समीक्षित मेल नहीं", emptyBody: "बताएँ कि आपको किस सहायता की ज़रूरत है और आपका खेत कहाँ है।", errorTitle: "यह जाँच पूरी नहीं हो सकी", retry: "फिर कोशिश करें", offline: "आप ऑफ़लाइन हैं। मौजूदा प्रोफ़ाइल दिखाई देगी; भेजना रुका है।",
  backConversation: "बातचीत पर वापस जाएँ", reviewedProfile: "आपकी पुष्ट प्रोफ़ाइल के आधार पर समीक्षा", resultsGuidance: "ये मार्गदर्शन परिणाम हैं, आधिकारिक स्वीकृति नहीं। सटीक शर्तें और प्रमाण देखने के लिए कोई कार्ड खोलें।", reviewedSources: "{count} समीक्षित स्रोत", refineProfile: "प्रोफ़ाइल सुधारें", demoCorpus: "डेमो संग्रह", demoCorpusBody: "ये काल्पनिक योजनाएँ समीक्षित कृत्रिम नीति रिकॉर्ड का उपयोग करती हैं। किसी वास्तविक किसान का डेटा नहीं दिखाया गया है।", schemeList: "योजना सिफारिशें", strongestMatch: "सबसे मजबूत समीक्षित मेल", conditionsPassed: "{passed} शर्तें पूरी", needsAttention: "{count} पर ध्यान ज़रूरी", allReviewed: "सभी समीक्षित", nextStep: "अगला कदम", whyThis: "ऐसा क्यों?", details: "विवरण", stopReading: "{name} पढ़ना रोकें", listenTo: "{name} सुनें", openScheme: "{name} खोलें", likelyEligible: "संभावित रूप से पात्र", notEligible: "प्रकाशित शर्त के अनुसार पात्र नहीं", needInformation: "और जानकारी चाहिए", manualReview: "मैन्युअल समीक्षा सुझाई गई",
  evidenceDetail: "प्रमाण विवरण", closeEvidence: "प्रमाण विवरण बंद करें", reviewedDemo: "समीक्षित डेमो डेटा", reviewedDemoBody: "यह काल्पनिक रिकॉर्ड स्रोत दर्शाता है। यह सक्रिय सरकारी योजना नहीं है।", whyMatched: "यह क्यों मेल खाता है", publishedConditions: "प्रकाशित शर्तें", resolved: "{passed}/{total} हल", evidence: "प्रमाण", documentReadiness: "दस्तावेज़ तैयारी", officialEvidence: "आधिकारिक स्रोत प्रमाण", reviewedDate: "{date} को समीक्षित", openSource: "स्रोत खोलें", ready: "तैयार", needed: "ज़रूरी", check: "जाँचें", allRecommendations: "सभी सिफारिशें", evidenceBacked: "प्रमाण-आधारित विवरण", detailDemoBody: "यह उत्पाद प्रदर्शन के लिए काल्पनिक योजना रिकॉर्ड है, सक्रिय सरकारी लाभ नहीं।", eligibilityConditions: "पात्रता की शर्तें", derivedFrom: "{sources} से प्राप्त", sourceProvenance: "स्रोत का विवरण", approvedReferences: "{count} स्वीकृत संदर्भ", yourNextStep: "आपका अगला कदम",
  footerTagline: "भारतीय किसानों के लिए प्रमाण-आधारित योजना मार्गदर्शन।", footerDisclaimer: "KisanPath समीक्षित प्रकाशित शर्तों के आधार पर मार्गदर्शन देता है। यह आधिकारिक पात्रता निर्णय जारी नहीं करता।", privacyEyebrow: "डिज़ाइन से स्पष्ट", privacyTitle: "गोपनीयता और सुरक्षा, सरल भाषा में।", privacyLead: "KisanPath को योजना खोज से संबंधित तथ्य ही चाहिए। आधार नंबर, बैंक पहचान या असंबंधित निजी जानकारी साझा न करें।", minimumTitle: "न्यूनतम आवश्यक तथ्य", minimumBody: "खेत का स्थान, भूमि क्षेत्र, फसल, स्वामित्व और आवश्यक सहायता समीक्षित शर्तों को प्रभावित कर सकते हैं।", reasoningTitle: "कोई छुपा तर्क नहीं", reasoningBody: "हम स्रोत, नियम परिणाम और स्थिति बदलाव जैसे संचालन ऑडिट रिकॉर्ड रखते हैं—निजी विचार-श्रृंखला नहीं।", neverApproval: "मार्गदर्शन, स्वीकृति नहीं", neverApprovalBody: "अंतिम निर्णय जिम्मेदार प्राधिकरण लेता है। KisanPath आवेदन जमा नहीं करता या वित्तीय कार्रवाई नहीं करता।",
  evalEyebrow: "बेसलाइन बनाम अंतिम वर्कफ़्लो", evalTitle: "मापी गई सुरक्षा, केवल डेमो की धारणा नहीं।", evalBody: "KisanPath समान स्थिर कृत्रिम मामलों पर बेसलाइन और अंतिम सिस्टम चलाता है। परिणाम पुनरुत्पादित और जाँच योग्य रहता है।", dataset: "डेटासेट", evalSnapshot: "मूल्यांकन झलक", evalNotice: "सीड मेट्रिक्स रिपोर्टिंग इंटरफ़ेस दिखाते हैं और उत्पादन प्रदर्शन का दावा नहीं हैं।", syntheticOnly: "केवल कृत्रिम मामले", mixedDataset: "मिश्रित डेटासेट", evalMetrics: "मूल्यांकन मेट्रिक्स", baseline: "बेसलाइन", safetyTitle: "स्थिर सीड सेट में शून्य गलत पात्रता परिणाम", safetyBody: "निश्चित विफलताएँ अवरोधक रहीं और लापता तथ्यों पर स्पष्टीकरण माँगा गया।", safetyPassed: "सुरक्षा जाँच पास", frozenDataset: "स्थिर कृत्रिम डेटासेट", caseExplorer: "केस एक्सप्लोरर", filterLanguage: "भाषा से मामले फ़िल्टर करें", all: "सभी", evalCases: "मूल्यांकन मामले", sanitizedInput: "साफ़ किया गया इनपुट", expected: "अपेक्षित", actual: "वास्तविक", auditNote: "ऑडिट नोट", trace: "इनपुट समझें → प्रोफ़ाइल सुधारें → नियम जाँचें → प्रमाण सत्यापित करें → उत्तर बनाएँ", somethingWrong: "कुछ गलत हुआ", loadFailed: "यह दृश्य लोड नहीं हो सका।", loadFailedBody: "कोई प्रोफ़ाइल तथ्य नहीं बदला। तैयार होने पर सुरक्षित अनुरोध फिर आज़माएँ।", tryAgain: "फिर कोशिश करें", pathMissing: "404 · रास्ता नहीं मिला", routeMissing: "यह रास्ता किसी समीक्षित परिणाम तक नहीं जाता।", routeMissingBody: "सहायक पर लौटें और बातचीत जारी रखें।", openAssistant: "सहायक खोलें",
};

const catalogs: Record<LanguageCode, Catalog> = {
  en,
  gu: { ...en, ...gu },
  hi: { ...en, ...hi },
};

export function translate(language: LanguageCode, key: TranslationKey, values: Record<string, string | number> = {}) {
  return Object.entries(values).reduce((message, [name, value]) => message.replaceAll(`{${name}}`, String(value)), catalogs[language][key]);
}
