import type {
  ConversationSnapshot,
  EvaluationReport,
  SchemeRecommendation,
} from "@/lib/contracts";

const irrigationSources = [
  {
    id: "synthetic-source-001",
    title: "Synthetic Micro-Irrigation Support Test Policy",
    publisher: "KisanPath reviewed demo corpus",
    locator: "Section 1 — jurisdiction",
    reviewedAt: "28 Aug 2026",
    excerpt:
      "This fictional support is available in Gujarat for agricultural micro-irrigation activity.",
    status: "approved" as const,
  },
  {
    id: "synthetic-source-002",
    title: "Synthetic Micro-Irrigation Support Test Policy",
    publisher: "KisanPath reviewed demo corpus",
    locator: "Section 2 — land threshold",
    reviewedAt: "28 Aug 2026",
    excerpt: "A fictional applicant must report no more than 2 hectares of agricultural land.",
    status: "approved" as const,
  },
];

export const seededSchemes: SchemeRecommendation[] = [
  {
    id: "synthetic-gujarat-irrigation",
    name: "Micro-Irrigation Support",
    shortName: "Irrigation support",
    status: "LIKELY_ELIGIBLE",
    benefitSummary: "A reviewed demo pathway for drip and micro-irrigation equipment support.",
    fitReason:
      "Your confirmed Gujarat location, groundnut crop, and 1.5 hectare holding match the reviewed conditions in this synthetic demonstration.",
    conditionsPassed: 4,
    conditionsTotal: 4,
    nextAction: "Review the document checklist before contacting the local agriculture office.",
    rules: [
      {
        id: "jurisdiction_gujarat",
        label: "Farm is located in Gujarat",
        result: "PASS",
        explanation: "Your confirmed profile says Anand, Gujarat.",
        sourceIds: ["synthetic-source-001"],
      },
      {
        id: "land_at_most_2_hectares",
        label: "Land area is no more than 2 hectares",
        result: "PASS",
        explanation: "1.5 hectares is within the reviewed demo threshold.",
        sourceIds: ["synthetic-source-002"],
      },
      {
        id: "activity_micro_irrigation",
        label: "Support requested for micro-irrigation",
        result: "PASS",
        explanation: "Drip irrigation was explicitly requested.",
        sourceIds: ["synthetic-source-001"],
      },
      {
        id: "ownership_recorded",
        label: "Land relationship is recorded",
        result: "PASS",
        explanation: "You confirmed that you own the land.",
        sourceIds: ["synthetic-source-002"],
      },
    ],
    documents: [
      {
        id: "land-record",
        label: "Current land record",
        detail: "Use the latest available record for the relevant plot.",
        status: "ready",
      },
      {
        id: "bank-detail",
        label: "Bank account detail",
        detail: "Check the official application channel before sharing any information.",
        status: "check",
      },
      {
        id: "equipment-quote",
        label: "Equipment quotation",
        detail: "A quotation may be needed during the application process.",
        status: "needed",
      },
    ],
    sources: irrigationSources,
    demo: true,
  },
  {
    id: "synthetic-farm-equipment",
    name: "Farm Equipment Access Support",
    shortName: "Equipment support",
    status: "INSUFFICIENT_INFORMATION",
    benefitSummary: "A fictional equipment-access pathway used to demonstrate safe clarification.",
    fitReason:
      "Your equipment need is relevant, but the reviewed demo rule requires a confirmed land-tenure value.",
    conditionsPassed: 2,
    conditionsTotal: 3,
    nextAction: "Confirm whether the land record lists you as owner or tenant.",
    rules: [
      {
        id: "equipment_gujarat",
        label: "Farm is located in Gujarat",
        result: "PASS",
        explanation: "Your confirmed profile says Gujarat.",
        sourceIds: ["synthetic-equipment-001"],
      },
      {
        id: "equipment_need",
        label: "Equipment support is relevant",
        result: "PASS",
        explanation: "Your request includes farm equipment support.",
        sourceIds: ["synthetic-equipment-001"],
      },
      {
        id: "tenure_confirmed",
        label: "Land tenure is confirmed",
        result: "UNKNOWN",
        explanation: "The current profile does not contain a confirmed tenure value.",
        sourceIds: ["synthetic-equipment-002"],
      },
    ],
    documents: [
      {
        id: "tenure-record",
        label: "Ownership or tenancy record",
        detail: "Needed to resolve the unanswered condition.",
        status: "needed",
      },
      {
        id: "equipment-detail",
        label: "Equipment requirement",
        detail: "Keep the requested equipment category ready.",
        status: "ready",
      },
    ],
    sources: [
      {
        id: "synthetic-equipment-001",
        title: "Synthetic Farm Equipment Access Policy",
        publisher: "KisanPath reviewed demo corpus",
        locator: "Section 1 — scope",
        reviewedAt: "28 Aug 2026",
        excerpt: "Fictional equipment access support is limited to agricultural use in Gujarat.",
        status: "approved",
      },
      {
        id: "synthetic-equipment-002",
        title: "Synthetic Farm Equipment Access Policy",
        publisher: "KisanPath reviewed demo corpus",
        locator: "Section 2 — land relationship",
        reviewedAt: "28 Aug 2026",
        excerpt: "The fictional applicant must provide a recorded land relationship for review.",
        status: "approved",
      },
    ],
    demo: true,
  },
  {
    id: "synthetic-water-stewardship",
    name: "Water Stewardship Pilot",
    shortName: "Water pilot",
    status: "MANUAL_REVIEW",
    benefitSummary: "A fictional pilot showing when policy interpretation must remain with a reviewer.",
    fitReason:
      "Your irrigation goal is relevant, but one reviewed condition cannot be resolved deterministically.",
    conditionsPassed: 2,
    conditionsTotal: 3,
    nextAction: "Ask the district agriculture office to review the local water-source condition.",
    rules: [
      {
        id: "water_location",
        label: "Farm is in a covered district",
        result: "PASS",
        explanation: "Anand is listed in the fictional demo coverage record.",
        sourceIds: ["synthetic-water-001"],
      },
      {
        id: "water_need",
        label: "Water-efficiency support requested",
        result: "PASS",
        explanation: "You requested drip irrigation support.",
        sourceIds: ["synthetic-water-001"],
      },
      {
        id: "local_water_source",
        label: "Local water-source condition",
        result: "MANUAL_REVIEW",
        explanation: "This condition requires local document review and was not guessed.",
        sourceIds: ["synthetic-water-002"],
      },
    ],
    documents: [
      {
        id: "water-record",
        label: "Water-source record",
        detail: "A local reviewer must verify this record.",
        status: "check",
      },
    ],
    sources: [
      {
        id: "synthetic-water-001",
        title: "Synthetic Water Stewardship Pilot Note",
        publisher: "KisanPath reviewed demo corpus",
        locator: "Section 1 — pilot coverage",
        reviewedAt: "28 Aug 2026",
        excerpt: "The fictional pilot covers selected agricultural districts and water-efficiency needs.",
        status: "approved",
      },
      {
        id: "synthetic-water-002",
        title: "Synthetic Water Stewardship Pilot Note",
        publisher: "KisanPath reviewed demo corpus",
        locator: "Section 3 — reviewer decision",
        reviewedAt: "28 Aug 2026",
        excerpt: "Local water-source records require manual review before a recommendation is made.",
        status: "approved",
      },
    ],
    demo: true,
  },
];

export const seededConversation: ConversationSnapshot = {
  id: "demo-conversation-001",
  language: "gu",
  stage: "START",
  messages: [
    {
      id: "welcome",
      role: "assistant",
      text: "નમસ્તે. તમે કઈ ખેતી સહાય શોધી રહ્યા છો? ગુજરાતી, हिन्दी અથવા Englishમાં કહી શકો છો.",
      language: "gu",
      timestamp: "10:24",
    },
  ],
  profile: [
    { id: "state", label: "રાજ્ય", value: "ગુજરાત", status: "confirmed", source: "voice" },
    { id: "district", label: "જિલ્લો", value: "આણંદ", status: "confirmed", source: "voice" },
    {
      id: "land_area",
      label: "જમીન",
      value: "3 એકર",
      status: "needs_confirmation",
      source: "voice",
      confidence: 0.61,
    },
    { id: "crop", label: "પાક", value: "મગફળી", status: "confirmed", source: "voice" },
  ],
  recommendations: [],
};

export const seededEvaluation: EvaluationReport = {
  datasetVersion: "kisanpath-synthetic-seed · v1.0.0",
  generatedAt: "29 Aug 2026, 11:40 IST",
  syntheticOnly: true,
  metrics: [
    {
      id: "classification",
      label: "Eligibility classification",
      description: "Exact expected outcome across the frozen synthetic cases.",
      baseline: 66.7,
      final: 100,
      unit: "%",
    },
    {
      id: "false-eligibility",
      label: "False eligibility rate",
      description: "Unsafe likely-eligible outcomes where the gold result is not eligible.",
      baseline: 16.7,
      final: 0,
      unit: "%",
      lowerIsBetter: true,
    },
    {
      id: "missing-info",
      label: "Missing-information detection",
      description: "Cases where unknown facts remain unknown and trigger clarification.",
      baseline: 50,
      final: 100,
      unit: "%",
    },
    {
      id: "citation",
      label: "Citation precision",
      description: "Consequential claims mapped to reviewed source references.",
      baseline: 58.3,
      final: 100,
      unit: "%",
    },
  ],
  cases: [
    {
      id: "likely_irrigation_en_001",
      title: "Clear irrigation match",
      language: "en",
      input: "I farm 1.5 hectares in Anand, Gujarat and need drip-irrigation support.",
      expected: "LIKELY_ELIGIBLE",
      actual: "LIKELY_ELIGIBLE",
      passed: true,
      note: "All required facts are explicit and every rule has reviewed provenance.",
    },
    {
      id: "not_eligible_jurisdiction_hi_002",
      title: "Blocking jurisdiction condition",
      language: "hi",
      input: "मैं कोटा, राजस्थान में एक हेक्टेयर जमीन का मालिक हूँ।",
      expected: "NOT_ELIGIBLE",
      actual: "NOT_ELIGIBLE",
      passed: true,
      note: "The deterministic state failure remains blocking.",
    },
    {
      id: "missing_land_area_en_003",
      title: "Land area is absent",
      language: "en",
      input: "I am a tenant farmer in Mehsana and need irrigation support.",
      expected: "INSUFFICIENT_INFORMATION",
      actual: "INSUFFICIENT_INFORMATION",
      passed: true,
      note: "No land area was inferred; the workflow asks a clarification.",
    },
    {
      id: "conflicting_ownership_en_004",
      title: "Conflicting ownership",
      language: "en",
      input: "The farm is mine, but the record lists me as a tenant.",
      expected: "MANUAL_REVIEW",
      actual: "MANUAL_REVIEW",
      passed: true,
      note: "Both alternatives remain in canonical profile state.",
    },
    {
      id: "ambiguous_bigha_gu_005",
      title: "Regional land unit",
      language: "gu",
      input: "મારી પાસે ત્રણ બીઘા જમીન છે અને મને સિંચાઈ સહાય જોઈએ છે.",
      expected: "INSUFFICIENT_INFORMATION",
      actual: "INSUFFICIENT_INFORMATION",
      passed: true,
      note: "Bigha is not normalized without reviewed regional context.",
    },
  ],
};
